services:
  nginx:
    image: nginx:1.29-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server1
      - server2
    networks:
      - backend

  server1:
    build: ./backend
    expose:
      - "3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/node_modules
    networks:
      - backend

  server2:
    build: ./backend
    expose:
      - "3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/node_modules
    networks:
      - backend

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=url_shortner
      - POSTGRES_PASSWORD=password_url_shortner
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:8.2-alpine
    volumes:
      - polls_redis_data:/data
    networks:
      - backend

volumes:
  polls_pg_data:
  polls_redis_data:

networks:
  backend:
    driver: bridge
