services:
  server:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/node_modules

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=url_shortner
      - POSTGRES_PASSWORD=password_url_shortner
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - polls_redis_data:/data

volumes:
  polls_pg_data:
  polls_redis_data:
